build:
  image: teaci/msys$$arch
  pull: true
  shell: msys$$arch
  commands:
    # TODO: remove this option when not anymore needed
    - if [ $$arch = 32 ]; then export DISABLE_QUALITY_CHECK=true; fi
    - ./ci-build.sh

matrix:
  arch:
    - 64
    - 32
#FIXME: When a matrix build is done, only the build status of the last job in a matrix is sent to notification plugins, this confuses our irc plugin, see https://github.com/drone/drone/issues/1459. Github pull request Web UI status and Tea CI Web UI status works fine with matrix build.
