#!/usr/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE=-release #-debug
STRIP=-strip #-nostrip
if  [ -z $1 ]; then
	echo "syntax - build-upload VERSION [GPGPHRASE]  [EMAIL]"	
else
	if  [ -z $2 ]; then
		$DIR/build-kf5  #RELEASE $STRIP -shared -install  -upload-version $1 
	else
		if  [ -z $3 ]; then
			$DIR/build-kf5 $RELEASE -shared $STRIP -install -sign $2 -upload-version $1 
		else
			$DIR/build-kf5 $RELEASE -shared $STRIP -install -sign $2 -upload-version $1 -email $3
		fi
	fi	
fi
