#!/usr/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -z $2 ]; then
if [ -z $1]; then
echo  -syntax build-install VERSION [GPG-PASSKEY] 
else
$DIR/./build-kf5  -release -shared -strip  -install -version $1 
fi
else
$DIR/./build-kf5  -release -shared -strip  -install -sign $2 -version $1 
fi
# 5.26.0-1v0.9

